### ISSUE TITLE
Support Cloze Deletions

### ISSUE THREAD

**Issue by Positron010** [lazy-void/inka#3]
Hi,
Thank you for building this! 
This is really not an issue, but a feature request. Supporting **cloze deletions** will be awesome. 
Thanks

**Comment by lazy-void** [comment]
I will split my answer into three parts: *design*, *ideology* and *technical implementation*.

### Design

There are programs that solve the same problem as **inka**. My main problem with them is that they use *esoteric* syntax to create cards. It usually looks like this:
```markdown
FRONT: front text here
BACK: back text here
TAGS: tag1 tag2
...
```

I wanted two things: a more natural way to create the cards and that the cards look good after markdown is rendered by the app I am using (these days it's Obsidian). This is why **inka** uses syntax of the ordered list and the quote from markdown. 

I have no idea how you can implement *cloze deletions* without usage of some *esoteric* syntax.

### Ideology

**cloze deletions** simplify creation of cards. But this simplification creates problems. It is much easier to create *bad* cards with **cloze deletions**. I read on Anki subreddit how people just copy text from book (or other source) and create from this text **cloze deletion** cards in Anki. I have done this myself several times in the past. And now I think this is the wrong approach.

I think you must understand material before memorizing it. And although this is a simple truth, it can be too easily forgotten. **front/back** cards are forcing you to think about material because you need to understand the topic in order to ask questions. I had times when I realized that I poorly understood topic when I tried to create cards.

Of course, I'm talking about memorizing ideas/concepts, not facts (word translations, historical dates, medical stuff etc.). But do you really need **cloze deletions** to memorize facts?

I mainly use my own experience here. So I could be wrong and there are cases where **cloze deletions** are really needed. I'm ready to consider them.

### Technical implementation
Based on the above, I have not designed **inka** architecture with several types of cards in mind. So in order to implement **cloze deletions**, I will need to rewrite significant portion of codebase. It can be done, but for this I need good motivation.

**Comment by lazy-void** [comment]
I suppose you can use curly braces to create **cloze deletions**. They just don't really fit into my original view of **inka** as I described it in the first comment.

I've read through Andy Matuschak thoughts and mostly agree. Immediately after reading I disagreed that:

> If the choice is between cloze prompts and nothing at all, the cloze prompts are definitely better!

It wasn't so obvious to me that creating bad flashcards is better than not creating them at all. But I think my approach to making only good flashcards (well, as good as I can make them) backfired. There were times when I didn’t start reading a book/article because I knew it would take a lot of energy to create cards, and not creating them would mean that I would forget most of the material. On the other hand, making flashcards that you know are bad seems like a waste of effort, and I just can't bring myself to do them. It seems that reading a book and making bad flashcards would be better than not reading at all, but I need to overcome the mental barrier to do this.

Well, using **cloze deletions** as a simple shortcut for Q/A flashcards doesn't justify efforts it will take to implement them. And I don't think there is a significant difference between these two:

```markdown
1. What is the capital of Egypt? {Cairo}.
```

```markdown
1. What is the capital of Egypt?

> Cairo
```

**cloze deletions** is definitely faster than creating multiple Q/A cards. If we alter your example a little:

```markdown
1. The capital of {Egypt} is {Cairo}.
```

This will produce two flashcards. To create the same cards with Front/Back you will need to put more effort:

```markdown
1. What is the capital of Egypt?

> Cairo

2. The capital of which country is called Cairo?

> Egypt
```

And **cloze deletions** are good for such cases. But we are approaching dangerous territory of *pattern matching*, as Matushchak calls it. 

I will work on implementing **closing deletes** after adding *MathJax* support, although I cannot guarantee that this will happen anytime soon.

**Comment by Positron010** [comment]
Hi @lazy-void,
Nice to talk to you again!

I appreciate that you took the time to go through my comment. Thanks also for sharing your personal experience. 

Looking forward to the implementation, and the future enhancements of Inka!
Good luck!

**Comment by lazy-void** [comment]
Hey @Positron010. I want your opinion on how *cloze deletions* will work in **inka**. My current thoughts are to have 3 possible syntaxes:
- Anki syntax: `{{c1::some text here}}`, `{{c1::some text here::hint}}`
- Explicit short syntax: `{1::some text here}`, `{1::some text here::hint}` (I see no reason to make multiple variations of this syntax like in **ankify_roam** and **Obsidian_to_Anki**)
- Implicit short syntax: `{some text here}`, `{some text here::hint}`

In *math* and *code* blocks, it will be possible to use only *Anki syntax* for reasons that are probably obvious. 

There is also a problem with the ordering [described](https://github.com/taylormitchell/ankify_roam#non-intuitive-behaviour) by the author of **ankify_roam**. The solution might be to replace (in markdown file) *implicit short syntax* with *explicit syntax* or *Anki syntax* after card was added (or synced) to Anki. I prefer the *Anki* syntax in this case, because otherwise, if there are also blocks of code or math with **cloze deletions**, we will have two different syntaxes in the card. I can also make this customizable with a config option.

**Comment by Positron010** [comment]
Hi @lazy-void ! 
Sorry for the late reply. Thanks for giving me this opportunity, & taking my suggestions in consideration!

The options you proposed are good options, & are the widely implemented options. So having them is great, & it will be even better if the **hint** functionality of _clozes_ in Anki was also implemented.

Here are a few suggestions, that you may freely reject, they are mere suggestions, & I know nothing about their technical aspects..

- Highlights are considered clozes.  This is implemented as an option in Obsidian_to_Anki, you can also implement it if you are targeting Obsidian.

- Sometimes, making clozes, or converting a selection of text into a cloze can be cumbersome, as one doesn't have a shortcut for it lie in Anki. I think we can make the process easier by making the syntax easier, and moving away from the curly braces, but I really don't know what technical aspects surround this suggestion. For example, you can identify clozes using a prefix that the user is unlikely to use normally like `cl1::` followed by the text that will be mad a cloze. Additionally, you can be more specific, by only detecting this cloze,if a certain tag is present. Something like this: 

```
This is a cl1::cloze #cloze
```

- This is a bit for somehow advanced users, but good if you care a lot about the design of clozes in the text. You can detect clozes if the text is surrounded by a `<span>` tag, with a certain _css_ class that you defined, to customise its look. For example:

```
<span class="myclass">cloze</span>
```


Again, these are _additional_ **suggestions**, with **no** understanding of the _implementation_ aspect, so take them with a grain of salt, and reject them as you see.

Hope this helps. Thanks.

**Comment by lazy-void** [comment]
It's an interesting idea to use == Highlight == as a cloze, but I can easily see at least one problem: in code blocks, `==` can be widely used. So this can be implemented, but must be disabled by default.

The problem with `cl1::` or something similar is that you can't hide multiple words with it. The curly braces explicitly indicate where the beginning and where the end of the cloze is. Sorry, I didn't understand the part about shortcuts. Did you mean there is no simpler syntax for clozes in Anki itself?

In the latter case, did you mean that someone would use a <span> to customize the appearance in a text editor or in Anki? In any case, it looks like what a small number of people will use. So I will not implement it myself.

**Comment by Positron010** [comment]
Hi @lazy-void ,

- You are right about the _highlight_  option. But it would be worthwhile to implement it as an option if you want to reach a greater audience. Not all people use code blocks.

- For the second option, you can mimic the curly braces. Ex. `cl1::cloze::`. By the lack of shortcut, I mean that unlike in Anki, where you can just select the text and press <kbd>ctrl+shift+c</kbd> to make it a cloze. In **Obsidian** for example, -unless you are an advanced user- you will need to wrap the text manually without the shortcut.

- The last case is concerned with the view of the clozes within the text editor like **Obsidian**. So you can define a style for clozes in your **custom css**, then apply it to the cloze to make it pop out in the text, which as you mentioned, won't be used unless you care about design.

Implementing the _curly braces_ syntax is in itself great. These are just additional suggestions. Thanks.

**Comment by lazy-void** [comment]
Feature was implemented in the last release. I'm closing the issue.

**Comment by Positron010** [comment]
Nice Work @lazy-void . Thanks.
